export LOGO=/images/bitkubchain-logo.png
export ETHEREUM_JSONRPC_VARIANT=geth
export ETHEREUM_JSONRPC_HTTP_URL=https://pubnodes.cypherium.io/
export ETHEREUM_JSONRPC_WS_URL=ws://218.185.241.160:8546
export ETHEREUM_JSONRPC_TRACE_URL=https://pubnodes.cypherium.io/
export BLOCKSCOUT_HOST=bkcscan.com
export BLOCKSCOUT_PROTOCOL=https
export NETWORK="Mainnet"
export SUBNETWORK="Cypherium Chain"
export BLOCK_TRANSFORMER=clique
export DISABLE_EXCHANGE_RATES=true
export ENABLE_TXS_STATS=true
export SHOW_PRICE_CHART=true
export SHOW_TXS_CHART=true
export COIN="CPH"
export COINGECKO_COIN_ID="Cypherium-Chain"
